# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 use_frameworks!
 target 'needUs' do
  pod 'AMap2DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'
  pod 'AMapNavi'
 end



